### ISSUE TITLE
Program does not run

### ISSUE THREAD

**Issue by ankushdharkar** [karthik1531/learning#1]
![image](https://user-images.githubusercontent.com/1935403/33903080-17cd26f2-df9d-11e7-8b7e-685bc2e974d8.png)

**Comment by karthik1531** [comment]
![screenshot from 2017-12-13 21-50-55](https://user-images.githubusercontent.com/26918025/33949510-ceb487fe-e04f-11e7-9b71-d8db63accd05.png)
